// ------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução: 15.0.0.0
//  
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for recriado.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Application.Domain.Notificacoes.EmailTemplate
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Application.Domain.Enums;
    using Application.Domain.Notificacoes.Model;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ArquivoProcessadoEmailTemplate : ArquivoProcessadoEmailTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
<!DOCTYPE html>
<html>
<head>
 <style>
        body {
            font-family: arial;
        }

        table {
            border-collapse: collapse;
        }

        td, th {
            border: 1px solid #dddddd;
            text - align: left;
            padding: 8px;
        }

        .linhaTopo {
            background-Color: #CFCFCF;
            font-weight: bold;
        }
    </style>
</head>

<body>
	<p>Foi processado o serviço de integração de arquivos do COTA+ com I4PRO</p>
    <p>Resultado do processamento: </p>
    <table>
        <thead>
            <tr class=""linhaTopo"">  
				<th>STATUS</th>
                <th>MENSAGEM</th>
                <th>Nº PROPOSTA</th>                                    
                <th>Nº APOLICE</th>
                <th>CHAVE</th>
                <th>DATA EMISSÃO</th>
            </tr>
        </thead>
		<tbody>
		");
            
            #line 51 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 foreach(var arquivo in ArquivosProcessados) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t\r\n\t\t\t");
            
            #line 53 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 if (arquivo.StatusProcessamentoArquivo == StatusPropostaArquivoEnum.NaoDefinido) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr style=\"\">\r\n\t\t\t");
            
            #line 55 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t");
            
            #line 57 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 if (arquivo.StatusProcessamentoArquivo == StatusPropostaArquivoEnum.Erro) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr style=\"background-color: #FF8E9A\" >\r\n\t\t\t");
            
            #line 59 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 60 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 if (arquivo.StatusProcessamentoArquivo == StatusPropostaArquivoEnum.Sucesso) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr style=\"background-color: #90FF75\" >\r\n\t\t\t");
            
            #line 62 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 63 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 if (arquivo.StatusProcessamentoArquivo == StatusPropostaArquivoEnum.Executando) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr style=\"background-color: #FFFACD\" >\r\n\t\t\t");
            
            #line 65 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 66 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 if (arquivo.StatusProcessamentoArquivo == StatusPropostaArquivoEnum.LoteArquivoInconsistente) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr style=\"background-color: #FFFACD\" >\r\n\t\t\t");
            
            #line 68 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 69 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 if (arquivo.StatusProcessamentoArquivo == StatusPropostaArquivoEnum.Alocado) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr style=\"\">\r\n\t\t\t");
            
            #line 71 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t<td>");
            
            #line 73 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arquivo.StatusProcessamentoArquivoDescricao));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 74 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arquivo.Mensagem == null ? string.Empty : arquivo.Mensagem));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 75 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arquivo.NumProposta == null ? string.Empty : arquivo.NumProposta));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 76 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arquivo.NumApolice == null ? string.Empty : arquivo.NumApolice));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 77 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arquivo.Chave == null ? string.Empty : arquivo.Chave));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 78 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arquivo.DtEmissaoFormatada == null ? string.Empty : arquivo.DtEmissaoFormatada));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t");
            
            #line 80 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</tbody>\r\n\t</table>          \r\n</body>\r\n</html>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 86 "F:\D\PREVISUL\C#\Previsul.Business.Services\Application.Domain\Notificacoes\EmailTemplate\ArquivoProcessadoEmailTemplate.tt"
 
    public List<ArquivoProcessado> ArquivosProcessados { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ArquivoProcessadoEmailTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
