USE master;
GO

-- Logs
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'PBS_LOG') 
BEGIN 
    EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'PBS_LOG' 
    ALTER DATABASE [Log] SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
    ALTER DATABASE [Log] SET SINGLE_USER 
    DROP DATABASE [Log] 
END 
GO

CREATE DATABASE [PBS_LOG];
GO

USE PBS_LOG;
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOG]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOG](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TIMESTAMP] [datetime] NOT NULL,
    [MACHINE_NAME] [varchar](32) NULL,
    [APPLICATION] [int] NOT NULL,
    [SEVERITY] [int] NOT NULL,
    [SOURCE] [varchar](255) NULL,
    [MESSAGE] [varchar](8000) NOT NULL,
    [REQUEST_ID] [uniqueidentifier] NULL,
    [IP_ADDRESS] [varchar](15) NULL,
CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[LOG]') AND name = N'IDX_ApplicationID_Severity_TimeStamp')
CREATE NONCLUSTERED INDEX [IDX_ApplicationID_Severity_TimeStamp] ON [dbo].[LOG]
(
    [APPLICATION] ASC,
    [SEVERITY] ASC,
    [TIMESTAMP] DESC
)
INCLUDE ([Id],
    [MACHINE_NAME],
    [SOURCE],
    [MESSAGE],
    [REQUEST_ID],
    [IP_ADDRESS]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE LOGIN APP_PBS_LOG WITH PASSWORD = '@4CUMAAVMNSL3O'
CREATE USER APP_PBS_LOG FROM LOGIN APP_PBS_LOG
EXEC sp_addrolemember 'DB_OWNER', 'APP_PBS_LOG' (edited)